//filters constant
const SORT_PRODUCTS = "SORT_PRODUCTS";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const PRICE_RANGE = "PRICE_RANGE";
const SORT_BY_RATING = "SORT_BY_RATING";
const SEARCH_ITEM = "SEARCH_ITEM";
const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
const TOGGLE_STOCK = "TOGGLE_STOCK";
//constants
const UPDATE_WISHLIST = "UPDATE_WISHLIST";
const UPDATE_CART = "UPDATE_CART";

export {
  SORT_PRODUCTS,
  CLEAR_FILTERS,
  PRICE_RANGE,
  SORT_BY_RATING,
  SEARCH_ITEM,
  FILTER_BY_CATEGORY,
  TOGGLE_STOCK,
  UPDATE_WISHLIST,
  UPDATE_CART,
};
