//filters constant

const SORT_PRODUCTS = "SORT_PRODUCTS";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const PRICE_RANGE = "PRICE_RANGE";
const SORT_BY_RATING = "SORT_BY_RATING";
const SEARCH_ITEM = "SEARCH_ITEM";
export {
  SORT_PRODUCTS,
  CLEAR_FILTERS,
  PRICE_RANGE,
  SORT_BY_RATING,
  SEARCH_ITEM,
};
