//filters constant

const SORT_PRODUCTS = "SORT_PRODUCTS";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const PRICE_RANGE = "PRICE_RANGE";
const STAR4_ABOVE = "STAR4_ABOVE";
const STAR3_ABOVE = " STAR3_ABOVE";
const STAR2_ABOVE = "STAR2_ABOVE";
export {
  SORT_PRODUCTS,
  CLEAR_FILTERS,
  PRICE_RANGE,
  STAR4_ABOVE,
  STAR3_ABOVE,
  STAR2_ABOVE,
};
